version: '3.8'
services:
  db:
    image: postgres:15
    container_name: medclinic-db
    restart: always
    environment:
      POSTGRES_USER: medclinic
      POSTGRES_PASSWORD: medclinic123
      POSTGRES_DB: medclinic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
